### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Krymancer** [Krymancer/TrabalhoBD#6]
Tela Principal:
- [x] Fazer requisições por nome
- [x] Fazer as requisições dos groupBoxes de cada Aba

Criar telas de Adicionar:
- [x] Criar telas de Adicionar Hotéis
- [x] Criar telas de Adicionar Restaurantes
- [x] Criar telas de Adicionar Igrejas
- [x] Criar telas de Adicionar Museus
- [x] Criar telas de Adicionar Casas de Show
- [x] Criar telas de Adicionar Fundadores
- [x] Criar telas de Adicionar Cidades

Criar telas de Detalhes
- [x] Criar telas de  Detalhes Hotéis
- [x] Criar telas de  Detalhes Restaurantes
- [x] Criar telas de  Detalhes Igrejas
- [x] Criar telas de  Detalhes Museus
- [x] Criar telas de  Detalhes Casas de Show
- [x] Criar telas de  Detalhes  Fundadores

Implementações dos Métodos de INSERT na classe DAL:
- [x] DAL Insert Hotel
- [x] DAL Insert Restaurante
- [x] DAL Insert Ponto Turístico
- [x] DAL Insert Igreja
- [x] DAL Insert Museu
- [x] DAL Insert Casa de Show
- [x] DAL Insert Fundador
- [x] DAL Insert Cidade
- [x] DAL Insert Usuário

Implementações dos Métodos de UPDATE na classe DAL:
- [x] DAL Update Hotel
- [x] DAL Update Restaurante
- [x] DAL Update Ponto Turístico
- [x] DAL Update Igreja
- [x] DAL Update Museu
- [x] DAL Update Casa de Show
- [x] DAL Update Fundador
- [x] DAL Update Cidade
- [x] DAL Update Usuário

Implementações dos Métodos de DELETE na classe DAL:
- [x] DAL Delete Hotel
- [x] DAL Delete Restaurante
- [x] DAL Delete Ponto Turístico
- [ ] DAL Delete Igreja
- [ ] DAL Delete Museu
- [x] DAL Delete Casa de Show
- [x] DAL Delete Fundador
- [x] DAL Delete Cidade
- [x] DAL Delete Usuário

Refatorações:
- [x] Refatorar pra implementar interpolação em todas as strings de query

Implementação dos Detalhes 
- [x] Detalhes Hotel
- [x] Detalhes Restaurante
- [x] Detalhes Casa de show
- [x] Detalhes Igreja
- [x] Detalhes Museu
- [x] Detalhes Fundador
